apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/rosa-hcp-terraform  # TODO: 実際のリポジトリURLに変更
    targetRevision: main
    path: platform
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
