apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Tanakan/terraform-hcp
    targetRevision: main
    path: apps/test-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
