apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-proxy-cookie
  namespace: test-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oauth-proxy-cookie
    creationPolicy: Owner
  data:
  - secretKey: cookie-secret
    remoteRef:
      key: rosa/test-app/oauth-proxy-cookie
      property: cookie-secret
