apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
  namespace: test-app
spec:
  to:
    kind: Service
    name: oauth2-proxy
  port:
    targetPort: 4180
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
